backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://test.schwimmverein-haren.de
locale: de

collections:
  - name: "wettkampfsport" # Used in routes, e.g., /admin/collections/blog
    label: "Wettkampfsport" # Used in the UI
    media_folder: "/public/images/uploads/wettkampfsport"
    public_folder: "/images/uploads/wettkampfsport"
    folder: "src/pages/wettkampfsport" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/MarkdownLayout.astro",
        }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "news-website"
        label: "Website News"
        file: "src/data/homepage-news.json"
        fields:
          - label: "News"
            name: "news"
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Inhalt, name: body, widget: text }
              - { label: Link, name: href, widget: string, required: false }
              - {
                  label: "Aktiv",
                  name: "active",
                  widget: "boolean",
                  default: true,
                }
      - name: "sidebar"
        label: "Sidebar"
        file: "src/data/homepage-sidebar.json"
        editor:
          preview: false
        fields:
          - label: "Sidebar"
            name: "sidebar"
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - label: "Bild"
                name: "image"
                widget: "image"
                media_folder: "/public/images/uploads/sidebar"
                public_folder: "/images/uploads/sidebar"
                media_library:
                  config:
                    multiple: false
              - { label: Link, name: href, widget: string }
              - {
                  label: "Externer Link",
                  name: "external",
                  widget: "boolean",
                  default: true,
                }
              - {
                  label: "Aktiv",
                  name: "active",
                  widget: "boolean",
                  default: true,
                }
      - name: "faqs"
        label: "Faqs"
        file: "src/data/homepage-faqs.json"
        editor:
          preview: false
        fields:
          - label: "Faqs"
            name: "faqs"
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
      - name: "downloads"
        label: "Downloads"
        file: "src/data/homepage-downloads.json"
        media_folder: "/public/downloads"
        public_folder: "/downloads"
        editor:
          preview: false
        fields:
          - label: "Downloads"
            name: "downloads"
            widget: "list"
            fields:
              - { label: Label, name: label, widget: string }
              - label: "Datei"
                name: "filename"
                widget: "file"
              - label: "Dateityp"
                name: "filetype"
                widget: "select"
                options: ["pdf", "excel", "word", "image"]
      - name: "protokolle"
        label: "Protokolle Jahreshauptversammlung"
        file: "src/data/ueberuns-protokolle.json"
        media_folder: "/public/downloads/protokolle"
        public_folder: "/downloads/protokolle"
        editor:
          preview: false
        fields:
          - label: "Protokolle Jahreshauptversammlung"
            name: "protokolle"
            widget: "list"
            fields:
              - { label: Label, name: label, widget: string }
              - label: "Datei"
                name: "filename"
                widget: "file"
              - label: "Dateityp"
                name: "filetype"
                widget: "select"
                options: ["pdf", "excel", "word", "image"]
      - name: "ansprechpartner"
        label: "Ansprechpartner"
        file: "src/data/ueberuns-ansprechpartner.json"
        media_folder: "/public/images/uploads/ansprechpartner"
        public_folder: "/images/uploads/ansprechpartner"
        editor:
          preview: false
        fields:
          - label: "Ansprechpartner"
            name: "ansprechpartner"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - { label: Bild, name: image, widget: image, required: true }
              - {
                  label: Funktion,
                  name: function,
                  widget: string,
                  required: true,
                }
              - { label: E-Mail, name: email, widget: string, required: false }
              - { label: Telefon, name: phone, widget: string, required: false }
